---
name: PR Check

on:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    name: Build Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: |
      contains(github.event.pull_request.changed_files, 'Containerfile') ||
      contains(github.event.pull_request.changed_files, '.go') ||
      contains(github.event.pull_request.changed_files, 'go.mod') ||
      contains(github.event.pull_request.changed_files, 'go.sum')
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: test:pr-${{ github.event.pull_request.number }}
          build-args: |
            VERSION=pr-${{ github.event.pull_request.number }}
            REVISION=${{ github.event.pull_request.head.sha }}

  lint:
    name: Lint Containerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: contains(github.event.pull_request.changed_files, 'Containerfile')
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Containerfile
          failure-threshold: error

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: |
      contains(github.event.pull_request.changed_files, '.md') ||
      contains(github.event.pull_request.changed_files, '.markdownlint.yaml')
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: "**/*.md"
